#
# Pull base image
# ---------------
FROM oraclelinux:7-slim as base-ol7-slim-enhanced

# Maintainer
# ----------
MAINTAINER ch-lam <ch.lambert@gmail.com>

# add mimimal stuff
RUN yum -y install vim 
